[package]
name = "biwa_hub_infrastructure"
version.workspace = true
edition.workspace = true

[dependencies]
biwa_hub_domain = { path = "../biwa_hub_domain" }
biwac_base = { path = "../../../../../compiler/src/biwac_base" }

async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
] }
